language: node_js
node_js:
    - "8.1.4"
sudo: false
install:
    - npm install -g electron
    - npm install
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
    - npm start
addons:
    apt:
        packages:
            - xvfb
